config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :comments
  resources :posts
  resources :likes, only: [:create, :destroy]
  resources :users
  resources :friend_requests, only: [:new, :index, :create, :destroy]
  resources :friendships, only: [:new, :create, :destroy]

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable, class_name: 'Comment'
    has_many :likes, as: :likeable

    validates :content, presence: true, length: {maximum: 500}
    validates :user_id, presence: true
    validates :commentable_id, presence: true
    validates :commentable_type, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include ApplicationHelper
    before_action :authenticate_user!
    def create
        @comment = Comment.create(comment_params)
        @comment.user_id = current_user.id
        @comment.save
        redirect_back or root_url
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])
        @comment.update_attributes(comment_params)
        redirect_back or root_url
    end

    def destroy
        @comment.destroy
        redirect_back or root_url
    end

    private
        def comment_params
            params.require(:comment).permit(:content, :commentable_id, :commentable_type)
        end

        def correct_user
            @comment = current_user.comments.find_by(id: params[:id])
            redirect_to root_url if @comment.nil?
        end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
    <div><%= link_to comment.user.name, comment.user %></div>
    <div><%= comment.content %></div>
    <% if comment.likes.count > 0 %>
        <div><%= "#{pluralize(comment.likes.count, 'person')} like this."%> </div>
    <% end %>
    <% if current_user.likes?(comment.id, comment.class.to_s) %>
        <%= render partial: 'likes/destroy_like', locals:{like: current_user.likes?(comment.id, comment.class.to_s)  }  %>
    <% else %>
        <%= render partial: 'likes/create_like', locals:{likeable_id: comment.id, likeable_type:comment.class.to_s } %>
    <% end %>
    <% if comment.user_id = current_user.id %>
        <%= link_to 'Edit', edit_comment_url(comment) %>
        <%= link_to 'Delete', comment, method: :delete %>
    <% end %>
    <%= render partial: 'comments/create_comment',  locals:{commentable_id: comment.id, commentable_type: comment.class.to_s }  %>
    <ul>
        <%= render comment.comments %>
    </ul>
</li>

app/views/comments/_create_comment.html.erb
<%= form_for Comment.new do |f| %>
  <%= f.text_area :content, placeholder: "Add a comment" %>
  <%= f.hidden_field :commentable_id, value: commentable_id %>
  <%= f.hidden_field :commentable_type, value: commentable_type %>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/comments/delete.html.erb
<%= form_for(delete_comment_url, 
             html: { method: :delete }) do |f| %>
  <%= f.submit "Delete", class: "btn" %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>
  <%= f.text_area :content, placeholder: "Add a comment" %>
  <%= f.hidden_field :commentable_id %>
  <%= f.hidden_field :commentable_type %>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>