config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :comments
  resources :posts
  resources :likes, only: [:create, :destroy]
  resources :users
  resources :friend_requests, only: [:new, :index, :create, :destroy]
  resources :friendships, only: [:new, :create, :destroy]

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, as: :commentable
    has_many :likes, as: :likeable

    validates :content, presence: true, length: {maximum: 500}
    validates :user_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include ApplicationHelper
    before_action :authenticate_user!
    def new
        @post = Post.new
    end

    def create

        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_back_or root_url
        else
            render 'new'
        end
    end

    def index
        @posts = Post.where(user_id: current_user.friend_ids)
        store_location
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_back_or root_url
        else
            render 'edit'
        end
    end

    def destroy
        @post.destroy
        redirect_back or root_url
    end

    private
        def post_params
            params.require(:post).permit(:content)
        end

        def correct_user
            @post = current_user.posts.find_by(id: params[:id])
            redirect_to root_url if @post.nil?
        end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_create_post.html.erb
<%= form_for(Post.new) do |f| %>
  <%= f.text_area :content, placeholder: "Whats on your mind..." %>
  <%= f.submit "Post"%>
<% end %>

app/views/posts/_post.html.erb
<li>
    <div><%= link_to post.user.name, post.user %></div>
    <div><%= post.content %></div>
    <% if post.likes.count > 0 %>
        <div><%= "#{pluralize(post.likes.count, 'person')} like this."%> </div>
    <% end %>
    <% if current_user.likes?(post.id, post.class.to_s) %>
        <%= render partial: 'likes/destroy_like', locals:{like: current_user.likes?(post.id, post.class.to_s)  }  %>
    <% else %>
        <%= render partial: 'likes/create_like', locals:{likeable_id: post.id, likeable_type:post.class.to_s } %>
    <% end %>
    <% if post.user_id = current_user.id %>
        <%= link_to 'Edit', edit_post_url(post) %>
        <%= link_to 'Delete', post, method: :delete %>
    <% end %>
    <%= render partial: 'comments/create_comment', locals:{commentable_id: post.id, commentable_type: post.class.to_s }  %>
    <ul>
        <%= render post.comments %>
    </ul>
</li>

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit "Post"%>
<% end %>

app/views/posts/index.html.erb
<%= render 'create_post' %>
<ul>
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
  <%= f.text_area :content, placeholder: "Whats on your mind..." %>
  <%= f.submit "Post"%>
<% end %>